version: '3'
services:
  user-service:
    build: ./user_service
    ports:
      - "8000:8000"
  order-service:
    build: ./order_service
    ports:
      - "8001:8001"
  restaurant-service:
    build: ./restuarant_service
    ports:
      - "8002:8002"
  notification-service:
    build: ./notification_service
    ports:
      - "8003:8003"
