FROM python:3.9-slim

WORKDIR /app

# Install curl and other utilities
RUN apt-get update && apt-get install -y curl

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy application code
COPY . .

# Expose the port used by Flask
EXPOSE 8001

# Run the application
CMD ["python3", "main.py"]

